### ISSUE TITLE
<img> not show

### ISSUE THREAD

**Issue by irsalshabirin** [PrivacyApps/html-textview#112]
when i have a string like this : 
`<img src=\"https://images.detik.com/community/media/visual/2017/06/29/be14d00c-1a73-4910-8d1f-76a874e86995_169.jpeg?w=620\" alt=\"Sekarang sudah banyak wisatawan yang datang (Usman Hadi/detikTravel)\"/>`

image url, has a parameter value. and image doesnt appear.
Please help me 👍

**Comment by DJafari** [comment]
@irsalshabirin you must pass an ImageGetter, sample :

```java
htmlTextView.setHtml("<img src=\"https://images.detik.com/community/media/visual/2017/06/29/be14d00c-1a73-4910-8d1f-76a874e86995_169.jpeg?w=620\" alt=\"Sekarang sudah banyak wisatawan yang datang (Usman Hadi/detikTravel)\"/>",
	new HtmlHttpImageGetter(htmlTextView));
```
