### ISSUE TITLE
can't handle html string of "\n"

### ISSUE THREAD

**Issue by fnzainal** [PrivacyApps/html-textview#116]
Hi, thanks You have nice library! :+1:
I think you have little bug, this library can't handle html string `\n`
let see this:

**code:**
```java
HtmlTextView htmlText = (HtmlTextView) findViewById(R.id.htmltext_artikel);
// get html string from api request
String html_string = data.getContent();
htmlText.setHtml(html_string);
```

**result :**
![device-2017-08-18-093707](https://user-images.githubusercontent.com/13946213/29442075-96a85df2-83f9-11e7-8daa-dcd42268b17e.png)

then I do some little trick way, and get better result:
**code:**
```java
HtmlTextView htmlText = (HtmlTextView) findViewById(R.id.htmltext_artikel);
String html_string = data.getContent();
String nice_html = html_string.replace("\n","<br>");
htmlText.setHtml(nice_html);
```
**result:**
![device-2017-08-18-093926](https://user-images.githubusercontent.com/13946213/29442074-9690406e-83f9-11e7-9371-220e14bba2fd.png)

Maybe You can add this on next release :)

**Comment by DJafari** [comment]
@fnzainal this library name is **HTML** textView, `\n` character is not a html tag, it just use in plain text
