### ISSUE TITLE
Alignment error in <ul> & <ol>

### ISSUE THREAD

**Issue by XYZ-College-Forum** [PrivacyApps/html-textview#123]
Hello,
The `<ul>` or `<ol>` tags work perfectly if any one is used a single time.
A successive use of any combination creates issue.
Example:
`<ul>...</ul>` (This will work as expected) `<ul>...</ul>` (This will give alignment issue).
`<ol>...</ol>` (This will again work as expected) `<ul>...</ul>` (This will give alignment issue).
`<ul>...</ul>` (This will again work as expected) `<ol>...</ol>` (This will get moved towards right by one space).
`<ol>...</ol>` (This will again work as expected) `<ol>...</ol>` (This will get moved towards right by one space).

So, successive `<ol>` just get shifted by one space without any other issue while, the bullets in `<ul>` get overlapped by the text.

Check screen-shot.
![screenshot_20171028-065939](https://user-images.githubusercontent.com/33169023/32130551-227367fa-bbb8-11e7-9593-1c61f3c13fac.png)
![screenshot_20171028-070036](https://user-images.githubusercontent.com/33169023/32130552-22baf912-bbb8-11e7-800d-ef58e8228a7d.png)
![screenshot_20171028-070101](https://user-images.githubusercontent.com/33169023/32130553-2303660c-bbb8-11e7-80e7-3987c2a127ba.png)
![screenshot_20171028-070114](https://user-images.githubusercontent.com/33169023/32130554-2348f15e-bbb8-11e7-86b2-86b3964dfab0.png)

**Comment by Fosile** [comment]
Any updates on this? I have the exact same problem...

**Comment by Alelelex** [comment]
Do you found any trick to fix that issue ? Same problem here.

**Comment by XYZ-College-Forum** [comment]
None that I know of. There's no commit regarding this.

**Comment by geet000** [comment]
I would also like to have solution for this.

**Comment by dschuermann** [comment]
Please try version 3.6. Should be fixed by https://github.com/PrivacyApps/html-textview/pull/142
