### ISSUE TITLE
Head content is being displayed

### ISSUE THREAD

**Issue by denison-mobimove** [PrivacyApps/html-textview#125]
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
			<title>Excel To HTML using codebeautify.org</title>
		</head>
		<body>
			<!DOCTYPE html>
			<html lang=en>
				<head>
					<meta charset=utf-8>
						<title>Budget Day Package at Ile Aux Cerfs</title>
						<link href=\"https://fonts.googleapis.com/css?family=Montserrat:200,300,400,600\" rel=stylesheet>
							<style>body{font-family:Montserrat,sans-serif;font-weight:300;font-size:14px;color:#333}strong{font-weight:600;}ul{line-height:20px;list-style-image:url('data:image/svg+xml;utf8,
								<svg width=\"8\" height=\"8\" viewBox=\"0 0 8 8\"
									xmlns=\"http://www.w3.org/2000/svg\">
									<title>ul_img</title>
									<desc>Created with Sketch.</desc>
									<circle cx=\"4\" cy=\"4\" r=\"4\" transform=\"translate(0 -6) translate(0 6)\" fill=\"#00AEC7\"/>
								</svg>');padding-left:20px}
							</style>
						</head>
						<body>
							<p>While you are on holidays in Mauritius, a gem that awaits you is the Ile aux Cerfs islet. If you are on the lookout for the perfect balance between relaxation, fun and water activities, you should definitely go for the Budget Day Package at Ile Aux Cerfs. The package includes a thrilling speed boat ride to the pristine Grand River South East waterfall and a lip-smacking BBQ lunch. You have the option to do water activities or just relax and swim in the azure lagoon.</p>
							<p>Your trip starts with a warm welcome by the enthusiastic and informative guide at Trou D’eau Douce (Parking-Four a Chaux). From there, you will experience a 15 minute ride at thrilling speed by boat, while being transferred to the gorgeous Ile aux Cerfs Island. Feast your eyes on the vivid turquoise colour of the lagoon, lush green casuarina and mangrove trees, not to mention the splendid and unique seashore with white soft sand.</p>
							<p>You can enjoy a leisurely stroll while your guide will give you a small brief of your day. Since this package is flexible depending on the wishes of the clients, you can either start with the water activities or with a trip to the Grand River South East waterfall located on the main land of Mauritius by speedboat. When you will be heading to the spellbinding waterfall you can cherish the pristine beauty of the surroundings, the lush greenery, and even encounter some monkeys near the waterfall.</p>
							<p>Now if you opt for water activities, you will enjoy the activities at one go in the vicinity of Ile aux Cerfs. You have the choice of doing one or all three activities from a panoply: parasailing, banana ride, tube ride, undersea walk. Those who do not feel like engaging in the water activities and swim in the lagoon or relax on the island.</p>
							<p>Regarding lunch, you will be heading to Ilot Mangenie-which is just next to Ile aux Cerfs- for a scrumptious BBQ, including drinks, and sometimes accompanied by a fun live entertainment!!</p>
						</body>
					</html>
				</body>
			</html>

**Comment by dschuermann** [comment]
not in scope for this lib to parse whole HTML pages.
