### ISSUE TITLE
styles are not working

### ISSUE THREAD

**Issue by sureace** [PrivacyApps/html-textview#132]
Hi,
       When i give html input as `<b>Hello</b><br/><ol><li>One</li><li><font style="color:#0000ff">Dhdjdjdjjd<br/></font></li><li><font style="color:#ffbf00">Fufjfhg</font></li></ol>` it is generating list as output without colors which are mentioned in style.
Thanks

**Comment by dschuermann** [comment]
style is not support, font is.

**Comment by dengyuhan** [comment]
maybe it can help you.
[dengyuhan/html-textview](https://github.com/dengyuhan/html-textview/blob/upgrade/NEW-README.md)
