### ISSUE TITLE
Is there anyway to override <a href=""> click events?

### ISSUE THREAD

**Issue by myatmins** [PrivacyApps/html-textview#134]
Currently if a user click a link on a hyperlink, it will open browser. Is there anyway to listen to that event?

**Comment by dschuermann** [comment]
Not supported currently.

**Comment by dengyuhan** [comment]
I added a custom click event for the a tag, you can try.
[dengyuhan/html-textview](https://github.com/dengyuhan/html-textview/blob/upgrade/NEW-README.md)

**Comment by sokarcreative** [comment]
Indeed it works with your library but make sure to call setOnClickUrlListener before setHtml
