### ISSUE TITLE
Is there support for span style e.g colors, background-colors?

### ISSUE THREAD

**Issue by KonradSzewczuk** [PrivacyApps/html-textview#135]
I've noticed that perhaps there is no support for colors(both text color and text background color).

Will it be supported?

**Comment by KonradSzewczuk** [comment]
UPDATE: 
For example i want to use such HTML string:

<p><span style="color: rgb(230, 0, 0);">should be text color red</span></p><p><br></p><p><br></p><p><span style="background-color: rgb(230, 0, 0);">should be text color red background</span></p>

**Comment by dschuermann** [comment]
No this is not and never will be supported. "<font size="..." color="..." face="...">" is supported.

**Comment by dengyuhan** [comment]
maybe it can help you.
[dengyuhan/html-textview](https://github.com/dengyuhan/html-textview/blob/upgrade/NEW-README.md)
