### ISSUE TITLE
Replace compile with implementation

### ISSUE THREAD

**Issue by RJFares** [PrivacyApps/html-textview#136]
My project keeps giving me this error and fortunately android studio now points to the library which has this problem.

Please replace 
```
dependencies {
    compile 'com.android.support:support-annotations:25.0.0'
}
```
with "implementation" (and any other if there is)

**Comment by dschuermann** [comment]
Can you make a pull request and fix this?

**Comment by RJFares** [comment]
Done.
I have never done this before so I hope I did it correctly :)

**Comment by dschuermann** [comment]
thanks!
