### ISSUE TITLE
Shows "table placeholder" instead of a table.

### ISSUE THREAD

**Issue by LeoDroidCoder** [PrivacyApps/html-textview#140]
Given html:
`<br /> <br /> <br /> <br /> &nbsp;<br/><br/><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:900px\"> <tbody> <tr> <td style=\"width:113px\"><span style=\"font-size:24px\">Location</span></td> <td style=\"width:19px\"><span style=\"font-size:24px\">:</span></td> <td style=\"width:495px\"><span style=\"font-size:24px\">Level 2, The Boulevard</span></td> </tr> <tr> <td style=\"width:113px\"><span style=\"font-size:24px\">Operation Hours</span></td> <td style=\"width:19px\"><span style=\"font-size:24px\">:</span></td> <td style=\"width:495px\"><span style=\"font-size:24px\">11:00am &ndash; 3:00pm; 6:00pm &ndash; 11:00pm</span></td> </tr> <tr> <td style=\"width:113px\"><span style=\"font-size:24px\">Reservations</span></td> <td style=\"width:19px\"><span style=\"font-size:24px\">:</span></td> <td style=\"width:495px\"><span style=\"font-size:24px\">(345) 8868 2822</span></td> </tr> </tbody> </table>`

Instead, it is displayed as "**table placeholder**"

**Comment by dschuermann** [comment]
Works as intended (see README)
